#!/bin/zsh

# https://apple.stackexchange.com/questions/465920/how-to-determine-details-of-backgound-process

sudo ${SUDO_ASKPASS:+-A} sfltool dumpbtm |
/usr/bin/awk 'BEGIN { capture=0 }

function f(field, dv) {
    if (field && field != "(null)") {
        return field
    } else {
        return (dv=="" ? "-" : dv)
    }
}

function fe(field) {
    if (field && field != "(null)") {
        return field
    }
}

/^ #/ { capture=1; next }
/^$/ { capture=0 }

capture {
    if (/UUID:/) { uuid=$2 }
    if (/URL:/) { url=$2 }
    if (/Type:/) { type=$0; sub(/^.*Type: /, "", type) }
    if (/Bundle Identifier:/) { bid=$3 }
    if (/^[[:space:]]+Name:/) { name=$0; sub(/^.*Name: /, "", name) }
    if (/Developer Name:/) { devname=$0; sub(/^.*Developer Name: /, "", devname) }
    if (/Executable Path:/) { execpath=$0; sub(/^.*Executable Path: /, "", execpath) }
}

/^$/ {
    if (fe(name) && fe(devname)) {
        cname = sprintf("%s (%s)", name, devname)
    } else {
        cname = sprintf("%s%s", fe(name), fe(devname))
    }
    if (type ~ /daemon/) { cname = "👿" cname }
    ue = fe(url) "|" fe(execpath)
    if (ue!="|" && a[ue]=="") {
        printf "%s\t%s\t%s\t%s\t%s\n", uuid, cname, bid, url, execpath
        a[ue]=1
    }
    uuid=url=type=bid=name=devname=execpath=cname=ue=""
}' |
/usr/bin/sort -k2
