#!/bin/zsh

# https://apple.stackexchange.com/questions/465920/how-to-determine-details-of-backgound-process

sudo ${SUDO_ASKPASS:+-A} sfltool dumpbtm |
/usr/bin/awk 'BEGIN { capture=0 }

/^ #/ { capture=1; next }
/^$/ { capture=0 }

capture {
    if (/UUID:/) { uuid=$2 }
    if (/URL:/) { url=$2 }
    if (/Bundle Identifier:/) { bid=$3 }
    if (/  Name:/) { name=$0; sub(/^.*  Name: /, "", name) }
    if (/Developer Name:/) { devname=$0; sub(/^.*Developer Name: /, "", devname) }
    if (/Executable Path:/) { execpath=$0; sub(/^.*Executable Path: /, "", execpath) }
}

/^$/ {
    if (url=="(null)") { url = "" }
    if (name=="(null)") { name = "" }
    if (devname=="(null)") { devname = "" }
    if (name && devname) {
        cname = sprintf("%s (%s)", name, devname)
    } else {
        cname = sprintf("%s%s", name, devname)
    }
    if (!uuid) { uuid = "-" }
    if (!bid) { bid = "-" }
    if (!cname) { cname = "-" }
    if (!url) { url = "-" }
    if (!execpath) { execpath = "-" }
    ue = url "|" execpath
    if (ue!="-|-" && a[ue]=="") {
        printf "%s\t%s\t%s\t%s\t%s\n", uuid, cname, bid, url, execpath
        a[ue]=1
    }
    uuid=bid=name=url=execpath=ue=""
}' |
/usr/bin/sort -k2
